### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ChocoChipset** [DarthMike/iOS-LocalizationsChecker#1]
We are missing a LICENSE for the use of our library. Any thoughts?

**Comment by DarthMike** [comment]
I propose [MIT](http://opensource.org/licenses/MIT)

**Comment by ChocoChipset** [comment]
Looks like the way to go. I will just made a quick comparison to be 100% sure.

**Comment by ChocoChipset** [comment]
Added License!
