### ISSUE TITLE
UITextfields obscured by password shouldn't be targeted 

### ISSUE THREAD

**Issue by ChocoChipset** [DarthMike/iOS-LocalizationsChecker#6]
Currently, UITextfields used to type passwords are being targeted by the library.

**Comment by ChocoChipset** [comment]
Couldn't reproduce.

**Comment by wyszo** [comment]
Not sure it's corrected - maybe worth testing on different iOS versions?

**Comment by DarthMike** [comment]
I can reproduce iOS 5.1, iPad 1st generation. Standard UITextField.

Can see that it shows incorrect behaviour after keyboard is dismissed (so user presses enter or chooses other textfield to be first responder). 

Can't see incorrect 'red' hightlights while user is writing on the textfield, and characters are rendered by symbols.

**Comment by DarthMike** [comment]
Repened, still can reproduce in some cases. Needs more investigation and testing
